import { Component, OnInit, ViewChild } from "@angular/core";
import {
  NgMDatatable,
  NgMDatatableOptions,
  PaginationMode
} from "projects/ng-m-datatable/src/public-api";

export interface Modelo {
  balance: any;
  age: number;
  eyeColor: any;
  name: any;
  gender: any;
  company: any;
  email: any;
  phone: any;
  address: any;
}

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.scss"],
})
export class HomeComponent implements OnInit {
  @ViewChild(NgMDatatable) DataTable: NgMDatatable<Modelo>;
  dataLength = 0;
  dataTableOptions: NgMDatatableOptions<Modelo> = {
    pagination: {
      mode: PaginationMode.Backend,
      pageSize: 10,
      change: (e) => {
        const d = this.rawData.slice(e.pageIndex * e.pageSize, (e.pageIndex + 1) * e.pageSize);
        this.data = d;
      },
    },
    filterSelect: {
      placeholder: "Filter",
      items: [
        {
          value: "brown",
          label: "Brown",
        },
        {
          value: "blue",
          label: "Blue",
        },
        {
          value: "",
          label: "All",
        },
      ],
      filter: (value, filterValue) => {
        return value.eyeColor === filterValue;
      },
      change: (value: any) => {
      },
    },
    columns: [
      { id: "balance", text: "Balance", type: "text" },
      { id: "age", text: "Edad", type: "text" },
      {
        id: "eyeColor",
        text: "Color de Ojos",
        color: "red",
        background: "yellow",
        type: "icon-button",
        icon: "fa fa-eye",
        handler: () => {
        },
      },
      { id: "name", text: "Nombre" },
      { id: "gender", text: "Genero", type: "badge" },
      {
        id: "action",
        text: "Actopms",
        type: "action",
        actions: [
          {
            text: "Edit",
            icon: "edit",
            handler: (data) => {
              console.log("Pressed Edit", data);
            },
          },
        ],
      },
    ],
    displayedColumns: [
      "balance",
      "age",
      "eyeColor",
      "name",
      "gender",
      "action",
    ],
    title: "Home Datatable Title! (Backend pagination)",
    addButton: {
      icon: "add",
      handler: () => {
        console.log("se preciono el boton de agregar");
      },
    },
  };

  rawData: Modelo[] = [];
  data: Modelo[] = [];
  filteredData: Modelo[] = [];

  ngOnInit() {
    setTimeout(() => {
      this.rawData = [
        {
          balance: "$3,845.96",
          age: 2,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 3,
          eyeColor: "brown",
          name: null,
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 4,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 5,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 6,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 7,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 8,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 9,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 10,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 11,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 12,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 13,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 14,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 15,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 16,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 17,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 18,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 19,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 20,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 21,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 22,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 23,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 24,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 25,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 26,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 27,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 28,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 29,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 30,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 31,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 32,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 33,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 34,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 35,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 36,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 37,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 38,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 39,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 40,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 41,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 42,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 43,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 44,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 45,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 46,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 47,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 48,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 49,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 50,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 51,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 52,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 53,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 54,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 55,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 56,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 57,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 58,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 59,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 60,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 61,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 62,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 63,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 64,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 65,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 66,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 67,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 68,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 69,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 70,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 71,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 72,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 73,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 74,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 75,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 76,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 77,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 78,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 79,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 80,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 81,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 82,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 83,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 84,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 85,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 86,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 87,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 88,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 89,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 90,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 91,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 92,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 93,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 94,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 95,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 96,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 97,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 98,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 99,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 100,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 101,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 102,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 103,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 104,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 105,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 106,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 107,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 108,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 109,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 110,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 111,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 112,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 113,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 114,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 115,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 116,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 117,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 118,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 119,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 120,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 121,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 122,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 123,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 124,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 125,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 126,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 127,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 128,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 129,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 130,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 131,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 132,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 133,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 134,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 135,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 136,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 137,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 138,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 139,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 140,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 141,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 142,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 143,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 144,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 145,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 146,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 147,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 148,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 149,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 150,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 151,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 152,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 153,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 154,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 155,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 156,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 157,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 158,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 159,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 160,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 161,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 162,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 163,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 164,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 165,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 166,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 167,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 168,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 169,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 170,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 171,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 172,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 173,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 174,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 175,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 176,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 177,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 178,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 179,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 180,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 181,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 182,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 183,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 184,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 185,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 186,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 187,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 188,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 189,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 190,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 191,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 192,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 193,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 194,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 195,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 196,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 197,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 198,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 199,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 200,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 201,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 202,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 203,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 204,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 205,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
      ];
      this.data = this.rawData.slice(0, this.dataTableOptions.pagination.pageSize);
      this.dataLength = this.rawData.length;
      console.log(this.data);

    }, 3000);
  }
}
