import { Component, OnInit, ViewChild } from "@angular/core";
import {
  NgMDatatable,
  NgMDatatableOptions,
} from "projects/ng-m-datatable/src/public-api";

export interface Modelo {
  balance: any;
  age: any;
  eyeColor: any;
  name: any;
  gender: any;
  company: any;
  email: any;
  phone: any;
  address: any;
}

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.scss"],
})
export class HomeComponent implements OnInit {
  @ViewChild(NgMDatatable) DataTable: NgMDatatable<Modelo>;
  dataTableOptions: NgMDatatableOptions<Modelo> = {
    columns: [
      { id: "balance", text: "Balance", type: "text" },
      { id: "age", text: "Edad", type: "text" },
      { id: "eyeColor", text: "Color de Ojos" },
      { id: "name", text: "Nombre" },
      { id: "gender", text: "Genero", type: "text" },
      {
        id: "action",
        text: "Actopms",
        type: "action",
        actions: [
          {
            text: "Edit",
            icon: "edit",
            handler: (data) => {
              console.log("Pressed Edit", data);
            },
          },
        ],
      },
    ],
    displayedColumns: [
      "balance",
      "age",
      "eyeColor",
      "name",
      "gender",
      "action",
    ],
    title: "Home Datatable Title!",
    addButton: {
      icon: "add",
      handler: () => {
        console.log("se preciono el boton de agregar");
      },
    },
  };

  data: Modelo[] = [];

  ngOnInit() {
    setTimeout(() => {
      this.data = [
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: null,
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
        {
          balance: "$3,845.96",
          age: 33,
          eyeColor: "brown",
          name: "Valarie Santos",
          gender: "female",
          company: "ELEMANTRA",
          email: "valariesantos@elemantra.com",
          phone: "+1 (816) 420-3640",
          address: "252 Wilson Street, Dunlo, American Samoa, 8802",
        },
        {
          balance: "$1,859.91",
          age: 34,
          eyeColor: "brown",
          name: "Mason Valentine",
          gender: "male",
          company: "RECRISYS",
          email: "masonvalentine@recrisys.com",
          phone: "+1 (829) 416-3339",
          address: "903 Prospect Street, Shasta, Illinois, 397",
        },
        {
          balance: "$3,157.01",
          age: 29,
          eyeColor: "blue",
          name: "Audra Duran",
          gender: "female",
          company: "MEDIFAX",
          email: "audraduran@medifax.com",
          phone: "+1 (896) 566-2090",
          address: "862 Forbell Street, Mayfair, Virgin Islands, 4836",
        },
        {
          balance: "$2,228.88",
          age: 21,
          eyeColor: "brown",
          name: "Maddox Olsen",
          gender: "male",
          company: "MINGA",
          email: "maddoxolsen@minga.com",
          phone: "+1 (979) 475-3654",
          address: "792 Newkirk Placez, Clayville, Idaho, 2083",
        },
        {
          balance: "$2,600.84",
          age: 37,
          eyeColor: "brown",
          name: "Corinne Puckett",
          gender: "female",
          company: "EARGO",
          email: "corinnepuckett@eargo.com",
          phone: "+1 (860) 542-3190",
          address: "457 Lacon Court, Greenfields, Oregon, 9401",
        },
        {
          balance: "$3,095.16",
          age: 30,
          eyeColor: "blue",
          name: "Harrington Cannon",
          gender: "male",
          company: "AUSTEX",
          email: "harringtoncannon@austex.com",
          phone: "+1 (813) 517-3004",
          address: "867 Locust Avenue, Finderne, Alaska, 5425",
        },
      ];
    }, 3000);
  }
}
